### PR TITLE
WIP: Add worker

### LINKED ISSUE #10: PDF Service
**Description** 
As a Content Manager I want PDF generation to be part of post-publication processing so that I can easily provide content in both Webview and PDF.

**Technical Notes**
Need a python developer to assist with this.
Implement post-publication webhooks
As part of the post-publication processing, trigger predefined webhooks to external services (i.e. pdf generation).
Verify the post-publication proc is available and configured within in cnx-deploy
Implement procedure in the post-publication process that calls a predefined/configured set of urls (webhook endpoints)
Role @trellouser --- olp: 2,9,12

Analysis: Design API for service (write user stories)
Aside: PZS thinks it would be nice to have a public page that shows build status (like travis-ci.org)
Progress? (pipe console messages?)
Success?
Errors?
Look into using the same interface (state and errors) cnx-publishing uses
Role @trellouser --- olp: 6,6,9

- AMQP to talk between BakedPDF and publishing(?)
- download HTML and images (to create the PDF)
- URL for hosting the resulting PDF
- Need a python developer to assist with this.

Implement PDF generation web service
Create a web service that generates PDFs for requested content.
Implement web service that utilizes the PDF building process implemented in previous tasks
Use Celery to allow for async builds of PDFs and persistence of requests
Role @trellouser --- olp: 9,9,9

 Configure PDF generation in cnx-deploy
Configure the web service and ancillary procs necessary to run the service as part of a deploy in cnx-deploy
Set up Flower for inspection of Celery tasks
Role @trellouser --- olp: 12,12,12

**Acceptance Criteria**
- When a user publishes any module or collection, the processes triggered include the PDF generation process for all books with that module, unless the book is locked for PDF generation. 
- After a book is published, the PDF is available on the web

**Link to Story in Epic Document**
https://docs.google.com/document/d/1Pm9X6zGH2KoZFtuZ7-fW04-MVGdzcwmFQ_a1Fs5GxQM/edit#heading=h.letpes6w68v1

### PR DESCRIPTION
**Pull request by aiwenar**
Resolves #10

## TODO

- [ ] Obtaining sources for processing
- [ ] Actual processing and PDF generation
- [ ] Logging
- [ ] Handling of errors in subprocesses
- [ ] Reporting
- [ ] Tests

And probably something more

### CODE REVIEW

**Comment by brittweinstein** [comment]
@helenemccarron can this be closed?

**Comment by helenemccarron** [comment]
@philschatz or @reedstrm what should we do with this? (I am not sure what the code does, if you have insights on what can be done to help merge it, please let me know)

**Comment by brittweinstein** [comment]
I will put this in the Icebox pipeline and Backlog milestone until clarification is provided in response to Helene's question.

**Comment by philschatz** [comment]
I think this can be closed. I think we shifted away from evolving mathify into a microservice and into it being used as a library.

/cc @brittweinstein

**Pull request closed without merging**
